services:
    # template-engine:
    #     container_name: template-engine
    #     build: './tempate-engine'
    #     ports:
    #         - 8081:8081
    #     networks:
    #         - frontend
    #         - backend
    #
    # api:
    #     container_name: api
    #     build: './api'
    #     ports:
    #         - 8080:8080
    #     networks:
    #         - frontend
    #         - backend

    db:
        container_name: mongodb
        build: './db'
        ports:
            - 27017:27017
            - 28017:28017

        volumes:
            - ./db/data:/data/db

        networks:
            - backend

    # ui:
    #     container_name: ui
    #     build: './ui'
    #     ports:
    #         - 4200:4200
    #     networks:
    #         - frontend

volumes:
    db:

networks:
    backend:
    frontend:
